-- DEPARTMENT
INSERT INTO DEPARTMENT VALUES ('M2349274', 'Mathematics');
INSERT INTO DEPARTMENT VALUES ('CS542016', 'Computer Science');
INSERT INTO DEPARTMENT VALUES ('FL203819', 'Foreign Languages');
INSERT INTO DEPARTMENT VALUES ('E9205375', 'English');
INSERT INTO DEPARTMENT VALUES ('PS190263', 'Political Science');
INSERT INTO DEPARTMENT VALUES ('H2038437', 'History');
INSERT INTO DEPARTMENT VALUES ('C3946510', 'Communication');
INSERT INTO DEPARTMENT VALUES ('B2319748', 'Biology');

-- STUDENT
INSERT INTO STUDENT VALUES ('RP031006', 'Rebecca', 'Therese', 'Post');
INSERT INTO STUDENT VALUES ('NW050506', 'Nicole', 'Katherine', 'Wood');
SELECT * FROM STUDENT;